### ISSUE TITLE
Replace grpc dependency with @grpc/grpc-js

### ISSUE THREAD

**Issue by chrnola** [walmartlabs/cookie-cutter#199]
The [`grpc` NPM package](https://www.npmjs.com/package/grpc) currently used by the cookie-cutter-grpc package is being deprecated in April 2021. From the package's readme:

> This library is now only receiving bug fixes and runtime compatibility updates. In April 2021 it will be deprecated and will no longer receive any updates.

The replacement package is [`@grpc/grpc-js`](https://www.npmjs.com/package/@grpc/grpc-js). This new package drops all the old native dependencies in favor of pure JavaScript implementations.

A feature comparison between the implementations can be found [here](https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md).

We should aim to upgrade the affected Cookie Cutter package before the deprecation date (roughly six months from now).

**Comment by plameniv** [comment]
Addressed by PR #360
