### ISSUE TITLE
Support ability to specify TTLs at item level when storing events to Azure CosmosDB

### ISSUE THREAD

**Issue by hienqnguyen** [walmartlabs/cookie-cutter#237]
We store events of different event streams in a single collection and would like to be able to set their TTLs differently.  Container level TTL is not granular enough for us.

Thus, we'd like to be able to specify the TTL at item level when storing an event. Per Azure [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2%2Cjavav4#nodejs-set-ttl-item), the item's level TTL will override the one specified at the container level.

**Comment by plameniv** [comment]
Work is complete and feature is deployed
