### ISSUE TITLE
Redis Client using bad label causing actual error messages to not propagate

### ISSUE THREAD

**Issue by prachi30** [walmartlabs/cookie-cutter#245]
Redis client is currently using [error object as a label](https://github.com/walmartlabs/cookie-cutter/blob/73cb200ee63858974b13ac5e7deb7da2f98447db/packages/redis/src/RedisClient.ts#L345) which is not an allowed data type for prometheus label and because of that we do not get actual error message logged in our app in a number of cases and all we see in logs is that bad label was used. We have seen our redis stream source getting stuck in a number of cases after this bad label error message so it would be helpful to get the labels fixed so we can get the actual error in logs.

It would also be great to get the data type for labels changed to `string | number` from `any` so we can avoid these issues in cc and also the apps using labels.

**Comment by plameniv** [comment]
Work is completed
