### ISSUE TITLE
Allow Kafka consumer client name to be configurable

### ISSUE THREAD

**Issue by cross311** [walmartlabs/cookie-cutter#317]
We are currently running cookie-cutter-kafka in a kubernetes cluster.  When seeing that a partition is lagged in our monitoring, we have to do a bunch of work to determine which pod is actually assigned that partition.  In the kafka group details it give you the client id or name that it is responsible for the partition.  It would be nice to be able to set the cluster and pod name as the client id so that you can quickly know which pod to look at.

**Comment by plameniv** [comment]
Kafka package generates the `clientId` as follows [`${getRootProjectPackageInfo().name}-${uuid.v4()}`](https://github.com/walmartlabs/cookie-cutter/blob/develop/packages/kafka/src/utils.ts#L14).

[`getRootProjectPackageInfo()`](https://github.com/walmartlabs/cookie-cutter/blob/develop/packages/core/src/utils/index.ts#L73) comes from the Core package and traverses the parent dirs to find a `package.json` which should have a name field.

A potential solution is to pass in a `clientId` prefix as part of the Kafka config and insert that at the beginning. `"<prefix>-<package name>-<uuid>"`
