### ISSUE TITLE
Investigate Potential Dead Lock

### ISSUE THREAD

**Issue by sklose** [walmartlabs/cookie-cutter#39]
Investigate if it is possible for an application to deadlock in Concurrent Mode when messages are redirected back to the input queue for reprocessing. If more messages require reprocessing than the size of the queue it might be possible that both queue processor "threads" are blocked on enqueuing something into a full queue.

**Comment by plameniv** [comment]
This issue may have been addressed by https://github.com/walmartlabs/cookie-cutter/pull/78

Closing.
