### ISSUE TITLE
Investigate Potential Infinite Loop If Retry Fails

### ISSUE THREAD

**Issue by sklose** [walmartlabs/cookie-cutter#41]
Following Situation:
* message A has a sequence conflict
* message B is being skipped, due to A's conflict
* A is retried, but the message handler fails (LogAndContinue mode)
* B is retried and succeeds

Is it possible that B enters an infinite retry loop because A failed to process and the flag to exit the retry loop never gets cleared?

**Comment by plameniv** [comment]
Was not observed since being open.
